# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetRooti <- function(Cov, Eye) {
    .Call('_spCP_GetRooti', PACKAGE = 'spCP', Cov, Eye)
}

QInvFnc <- function(WAlpha, EyeM, Rho, M) {
    .Call('_spCP_QInvFnc', PACKAGE = 'spCP', WAlpha, EyeM, Rho, M)
}

QFnc <- function(WAlpha, EyeM, Rho, M) {
    .Call('_spCP_QFnc', PACKAGE = 'spCP', WAlpha, EyeM, Rho, M)
}

WAlphaFnc <- function(Alpha, DMLong, AdjacentEdgesBoolean, W, M, WeightsInd) {
    .Call('_spCP_WAlphaFnc', PACKAGE = 'spCP', Alpha, DMLong, AdjacentEdgesBoolean, W, M, WeightsInd)
}

spCP_Rcpp <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('_spCP_spCP_Rcpp', PACKAGE = 'spCP', DatObj_List, HyPara_List, MetrObj_List, Para_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

Test <- function() {
    invisible(.Call('_spCP_Test', PACKAGE = 'spCP'))
}

GetXThetaLoc <- function(ThetaLoc, Time, OneNu, Nu) {
    .Call('_spCP_GetXThetaLoc', PACKAGE = 'spCP', ThetaLoc, Time, OneNu, Nu)
}

CreatePhi <- function(Beta, Lambda, Eta, M) {
    .Call('_spCP_CreatePhi', PACKAGE = 'spCP', Beta, Lambda, Eta, M)
}

CholInv <- function(Cov) {
    .Call('_spCP_CholInv', PACKAGE = 'spCP', Cov)
}

Inv3 <- function(A) {
    .Call('_spCP_Inv3', PACKAGE = 'spCP', A)
}

makeSymm <- function(A) {
    .Call('_spCP_makeSymm', PACKAGE = 'spCP', A)
}

